#include "WebPage.h"

const char* WEB_PAGE = "<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>Desk control</title>\n"
"    <style>\n"
"        /* Add some styling for better layout */\n"
"        body {\n"
"            font-family: Arial, sans-serif;\n"
"            margin-bottom: 20px;\n"
"            background-color: #e0e0e0; /* Light blue background */\n"
"        }\n"
"\t\t\n"
"\t\tbutton {\n"
"\t\t\tmargin-bottom: 7px;\n"
"\t\t\theight:20px;\n"
"\t\t\twidth:70px;\n"
"\t\t}\n"
"\t\t\n"
"\t\tinput {\n"
"\t\t\tmargin-right: 5px;\n"
"\t\t\tmargin-bottom: 7px;\n"
"\t\t}\n"
"\t\t\n"
"\t\tlabel {\n"
"\t\t\tmargin-bottom: 10px;\n"
"\t\t}\n"
"\n"
"\t\ttable {\n"
"\t\t\ttable-layout: fixed;\n"
"\t\t\twidth: 150px;\n"
"\t\t\tmargin-bottom: 5px;\n"
"\t\t}\n"
"\n"
"        h1 {\n"
"            margin-bottom: 10px;\n"
"            color: #333; /* Dark text color */\n"
"\t\t\tfont-size: 28px\n"
"        }\n"
"\n"
"        h2 {\n"
"            margin-bottom: 10px;\n"
"            color: #333; /* Dark text color */\n"
"\t\t\tfont-size: 20px\n"
"        }\n"
"\n"
"    </style>\n"
"</head>\n"
"<body onload=\"reload()\">\n"
"\n"
"\t<h1>Awesome Desk Controller &reg;</h1>\n"
"\n"
"    <h2>Drive manual</h2>\n"
"\t<div id=\"driveManual\">\n"
"\t\t<button onclick=\"driveDirection('up')\" style=\"width: 100px; height: 25px\">&uarr;</button>\n"
"\t\t<br>\n"
"\t\t<button onclick=\"driveStop()\" style=\"width: 100px; height: 25px\">--</button>\n"
"\t\t<br>\n"
"\t\t<button onclick=\"driveDirection('down')\" style=\"width: 100px; height: 25px\">&darr;</button>\n"
"\t</div>\n"
"\n"
"    <h2>Drive to</h2>\n"
"\t<div id=\"driveTo\">\n"
"\t\t<input type=\"text\" id=\"driveToEntry\">\n"
"\t\t<button onclick=\"driveTo(document.getElementById('driveToEntry').value)\">Go</button>\n"
"\t</div>\n"
"\t\n"
"    <h2>Presets</h2>\n"
"    <div id=\"presetsColumn\">\n"
"    </div>\n"
"    <button onclick=\"savePresets()\" style=\"margin-top: 10px; width: 100px\">Save</button>\n"
"\t\n"
"    <h2>Calibration</h2>\n"
"    <div>\n"
"\t\t<table>\n"
"\t\t\t<tr>\n"
"\t\t\t\t<td><label for=\"eHeight\">Height:</label></td>\n"
"\t\t\t\t<td><input type=\"text\" id=\"eHeight\"></td>\n"
"\t\t\t</tr>\n"
"\t\t</table>\n"
"        <button onclick=\"saveCalibration()\" style=\"width: 100px\">Save</button>\n"
"    </div>\n"
"\n"
"    <h2>Power</h2>\n"
"    <div>\n"
"\t\t<table>\n"
"\t\t\t<tr>\n"
"\t\t\t\t<td><label for=\"ePowerTimeout\">Timeout:</label></td>\n"
"\t\t\t\t<td><input type=\"text\" id=\"ePowerTimeout\"></td>\n"
"\t\t\t</tr>\n"
"\t\t</table>\n"
"        <button onclick=\"savePower()\" style=\"width: 100px\">Save</button>\n"
"    </div>\n"
"\n"
"    <h2>Wifi STA</h2>\n"
"    <div id=\"staSection\">\n"
"\t\t<table>\n"
"\t\t\t<tr>\n"
"\t\t\t\t<td><label for=\"eStaSsid\">Ssid:</label></td>\n"
"\t\t\t\t<td><input type=\"text\" id=\"eStaSsid\"></td>\n"
"\t\t\t</tr>\n"
"\t\t\t<tr>\n"
"\t\t\t\t<td><label for=\"eStaPass\">Pass:</label></td>\n"
"\t\t\t\t<td><input type=\"password\" id=\"eStaPass\"></td>\n"
"\t\t\t</tr>\n"
"\t\t\t<tr>\n"
"\t\t\t\t<td><label for=\"eStaIp\">Address:</label></td>\n"
"\t\t\t\t<td><input type=\"text\" id=\"eStaIp\"></td>\n"
"\t\t\t</tr>\n"
"\t\t\t<tr>\n"
"\t\t\t\t<td><label for=\"eStaGateway\">Gateway:</label></td>\n"
"\t\t\t\t<td><input type=\"text\" id=\"eStaGateway\"></td>\n"
"\t\t\t</tr>\n"
"\t\t\t<tr>\n"
"\t\t\t\t<td><label for=\"eStaSubnet\">Subnet:</label></td>\n"
"\t\t\t\t<td><input type=\"text\" id=\"eStaSubnet\"></td>\n"
"\t\t\t</tr>\n"
"\t\t</table>\n"
"\t\t<button onclick=\"saveSTA()\" style=\"width: 100px\">Save</button>\n"
"    </div>\n"
"\t\n"
"    <h2>Wifi AP</h2>\n"
"    <div id=\"apSection\">\n"
"\t\t<table>\n"
"\t\t\t<tr>\n"
"\t\t\t\t<td><label for=\"eApSsid\">Ssid:</label></td>\n"
"\t\t\t\t<td><input type=\"text\" id=\"eApSsid\"></td>\n"
"\t\t\t</tr>\n"
"\t\t\t<tr>\n"
"\t\t\t\t<td><label for=\"eStaPass\">Pass:</label></td>\n"
"\t\t\t\t<td><input type=\"password\" id=\"eApPass\"></td>\n"
"\t\t\t</tr>\n"
"\t\t\t<tr>\n"
"\t\t\t\t<td><label for=\"eStaIp\">Address:</label></td>\n"
"\t\t\t\t<td><input type=\"text\" id=\"eApIp\"></td>\n"
"\t\t\t</tr>\n"
"\t\t\t<tr>\n"
"\t\t\t\t<td><label for=\"eStaGateway\">Gateway:</label></td>\n"
"\t\t\t\t<td><input type=\"text\" id=\"eApGateway\"></td>\n"
"\t\t\t</tr>\n"
"\t\t\t<tr>\n"
"\t\t\t\t<td><label for=\"eStaSubnet\">Subnet:</label></td>\n"
"\t\t\t\t<td><input type=\"text\" id=\"eApSubnet\"></td>\n"
"\t\t\t</tr>\n"
"\t\t</table>\n"
"\t\t<button onclick=\"saveAP()\" style=\"width: 100px\">Save</button>\n"
"    </div>\n"
"\t\n"
"\t\n"
"    <h2>Maintenance</h2>\n"
"\t<div id=\"driveTo\">\n"
"\t\t<button onclick=\"restart()\" style=\"width: 100px\">Restart</button>\n"
"\t</div>\n"
"\n"
"    <script>\n"
"\t\t//var IP_ADDR = \"http://192.168.0.115\"\n"
"\t\tvar IP_ADDR = \"\"\n"
"\t\n"
"        function reload() {\n"
"            var xhr = new XMLHttpRequest();\n"
"            xhr.open('GET', IP_ADDR + '/health', true);\n"
"            xhr.onreadystatechange = function () {\n"
"                if (xhr.readyState == 4 && xhr.status == 200) {\n"
"                    var data = JSON.parse(xhr.responseText);\n"
"                    updateUI(data);\n"
"                }\n"
"            };\n"
"            xhr.send();\n"
"        }\n"
"\n"
"        function updateUI(data) {\n"
"            document.getElementById('eHeight').value = data.status.height;\n"
"\t\t\t\n"
"\t\t\tdocument.getElementById('ePowerTimeout').value = data.config.power.timeout;\n"
"\t\t\t\n"
"            document.getElementById('eStaSsid').value = data.config.wifiSTA.ssid;\n"
"            document.getElementById('eStaPass').value = data.config.wifiSTA.pass;\n"
"            document.getElementById('eStaIp').value = data.config.wifiSTA.ip;\n"
"            document.getElementById('eStaGateway').value = data.config.wifiSTA.gateway;\n"
"\t\t\tdocument.getElementById('eStaSubnet').value = data.config.wifiSTA.subnet;\n"
"\t\t\t\n"
"            document.getElementById('eApSsid').value = data.config.wifiAP.ssid;\n"
"            document.getElementById('eApPass').value = data.config.wifiAP.pass;\n"
"            document.getElementById('eApIp').value = data.config.wifiAP.ip;\n"
"            document.getElementById('eApGateway').value = data.config.wifiAP.gateway;\n"
"\t\t\tdocument.getElementById('eApSubnet').value = data.config.wifiAP.subnet;\n"
"\t\t\t\n"
"\t\t\t\n"
"\t\t\t\n"
"\t\t\tvar presetsColumn = document.getElementById('presetsColumn');\n"
"\t\t\tvar presetCnt = data.config.drive.presetsMax;\n"
"\t\t\tvar presets = data.config.drive.presets;\n"
"\n"
"            presetsColumn.innerHTML = '';\n"
"\t\t\t\n"
"\t\t\tfor(let i = 0; i < presetCnt; i++)\n"
"\t\t\t{\n"
"                var entry = document.createElement('input');\n"
"                entry.type = 'text';\n"
"\t\t\t\n"
"\t\t\t\tif(i < presets.length)\n"
"\t\t\t\t{\n"
"\t\t\t\t\tentry.value = presets[i];\n"
"\t\t\t\t\t\n"
"\t\t\t\t\tvar goButton = document.createElement('button');\n"
"\t\t\t\t\tgoButton.innerText = 'Go';\n"
"\t\t\t\t\tgoButton.style = \"margin-left: 5px\"\n"
"\t\t\t\t\tgoButton.onclick = function () {\n"
"\t\t\t\t\t\tdriveTo(presets[i]);\n"
"\t\t\t\t\t};\n"
"\t\t\t\t}\n"
"\t\t\t\t\n"
"\t\t\t\tpresetsColumn.appendChild(entry);\n"
"\t\t\t\t\n"
"\t\t\t\tif(i < presets.length)\n"
"\t\t\t\t{\n"
"\t\t\t\t\tpresetsColumn.appendChild(goButton);\n"
"\t\t\t\t}\n"
"\t\t\t\t\n"
"\t\t\t\tpresetsColumn.appendChild(document.createElement('br'));\n"
"\t\t\t}\n"
"        }\n"
"\t\t\n"
"\t\tfunction restart() {\n"
"            var xhr = new XMLHttpRequest();\n"
"            xhr.open('POST', IP_ADDR + '/restart', true);\n"
"\n"
"            xhr.onreadystatechange = function () {\n"
"                if (xhr.readyState == 4 && xhr.status == 200) {\n"
"                    console.log('Restart request sent.');\n"
"                }\n"
"            };\n"
"\n"
"            xhr.send();\n"
"\t\t}\n"
"\n"
"        function driveTo(height) {\n"
"            var xhr = new XMLHttpRequest();\n"
"            xhr.open('POST', IP_ADDR + '/drive/height', true);\n"
"            xhr.setRequestHeader('Content-Type', 'application/json');\n"
"\n"
"            xhr.onreadystatechange = function () {\n"
"                if (xhr.readyState == 4 && xhr.status == 200) {\n"
"                    console.log('Height preset sent successfully.');\n"
"                }\n"
"            };\n"
"\n"
"            xhr.send(JSON.stringify({ height: height }));\n"
"        }\n"
"\n"
"        function driveDirection(direction) {\n"
"            var xhr = new XMLHttpRequest();\n"
"            xhr.open('POST', IP_ADDR + '/drive/direction', true);\n"
"            xhr.setRequestHeader('Content-Type', 'application/json');\n"
"\n"
"            xhr.onreadystatechange = function () {\n"
"                if (xhr.readyState == 4 && xhr.status == 200) {\n"
"                    console.log('Direction sent successfully.');\n"
"                }\n"
"            };\n"
"\n"
"            xhr.send(JSON.stringify({ direction: direction }));\n"
"        }\n"
"\n"
"        function driveStop() {\n"
"            var xhr = new XMLHttpRequest();\n"
"            xhr.open('POST', IP_ADDR + '/drive/stop', true);\n"
"\n"
"            xhr.onreadystatechange = function () {\n"
"                if (xhr.readyState == 4 && xhr.status == 200) {\n"
"                    console.log('Drive stopped successfully.');\n"
"                }\n"
"            };\n"
"\n"
"            xhr.send();\n"
"        }\n"
"\t\t\n"
"        function savePresets() {\n"
"            var entries = document.querySelectorAll('#presetsColumn input');\n"
"            var presets = [];\n"
"\n"
"            entries.forEach(function (entry) {\n"
"\t\t\t\n"
"                presets.push(parseFloat(entry.value));\n"
"            });\n"
"\n"
"            var xhr = new XMLHttpRequest();\n"
"            xhr.open('POST', IP_ADDR + '/config', true);\n"
"            xhr.setRequestHeader('Content-Type', 'application/json');\n"
"\n"
"            xhr.onreadystatechange = function () {\n"
"                if (xhr.readyState == 4 && xhr.status == 200) {\n"
"                    console.log('Presets saved successfully.');\n"
"                }\n"
"            };\n"
"\n"
"            xhr.send(JSON.stringify({ config: {drive: {presets: presets}} }));\n"
"        }\n"
"\n"
"        function saveCalibration() {\n"
"            var heightVal = document.getElementById('eHeight').value;\n"
"\n"
"            var xhr = new XMLHttpRequest();\n"
"            xhr.open('POST', IP_ADDR + '/drive/calibration', true);\n"
"            xhr.setRequestHeader('Content-Type', 'application/json');\n"
"\n"
"            xhr.onreadystatechange = function () {\n"
"                if (xhr.readyState == 4 && xhr.status == 200) {\n"
"                    console.log('Calibration saved successfully.');\n"
"                }\n"
"            };\n"
"\n"
"            xhr.send(JSON.stringify({ height: parseFloat(heightVal) }));\n"
"        }\n"
"\t\t\n"
"        function savePower() {\n"
"            var timeoutVal = document.getElementById('ePowerTimeout').value;\n"
"\n"
"            var xhr = new XMLHttpRequest();\n"
"            xhr.open('POST', IP_ADDR + '/config', true);\n"
"            xhr.setRequestHeader('Content-Type', 'application/json');\n"
"\n"
"            xhr.onreadystatechange = function () {\n"
"                if (xhr.readyState == 4 && xhr.status == 200) {\n"
"                    console.log('Power saved successfully.');\n"
"                }\n"
"            };\n"
"\n"
"            xhr.send(JSON.stringify({ config: {power: {timeout: timeoutVal}} }));\n"
"        }\n"
"\t\t\n"
"\n"
"        function saveSTA() {\n"
"            var ssid = document.getElementById('eStaSsid').value;\n"
"            var pass = document.getElementById('eStaPass').value;\n"
"            var addr = document.getElementById('eStaIp').value;\n"
"\t\t\tvar gateway = document.getElementById('eStaGateway').value;\n"
"            var subnet = document.getElementById('eStaSubnet').value;\n"
"\n"
"            var xhr = new XMLHttpRequest();\n"
"            xhr.open('POST', IP_ADDR + '/config', true);\n"
"            xhr.setRequestHeader('Content-Type', 'application/json');\n"
"\n"
"            xhr.onreadystatechange = function () {\n"
"                if (xhr.readyState == 4 && xhr.status == 200) {\n"
"                    console.log('Network configuration saved successfully.');\n"
"                }\n"
"            };\n"
"\n"
"            xhr.send(JSON.stringify({config:{wifiSTA:{ ssid: ssid, pass: pass, ip: addr, gateway: gateway, subnet: subnet }}}));\n"
"        }\n"
"\t\t\n"
"        function saveAP() {\n"
"            var ssid = document.getElementById('eApSsid').value;\n"
"            var pass = document.getElementById('eApPass').value;\n"
"            var addr = document.getElementById('eApIp').value;\n"
"\t\t\tvar gateway = document.getElementById('eApGateway').value;\n"
"            var subnet = document.getElementById('eApSubnet').value;\n"
"\n"
"            var xhr = new XMLHttpRequest();\n"
"            xhr.open('POST', IP_ADDR + '/config', true);\n"
"            xhr.setRequestHeader('Content-Type', 'application/json');\n"
"\n"
"            xhr.onreadystatechange = function () {\n"
"                if (xhr.readyState == 4 && xhr.status == 200) {\n"
"                    console.log('Network configuration saved successfully.');\n"
"                }\n"
"            };\n"
"\n"
"            xhr.send(JSON.stringify({config:{wifiAP:{ ssid: ssid, pass: pass, ip: addr, gateway: gateway, subnet: subnet }}}));\n"
"        }\n"
"\t\t\n"
"    </script>\n"
"\n"
"</body>\n"
"</html>\n"
"";


const char* GetWebPage()
{
    return WEB_PAGE;
}